const languages={
  "English (Transatlantic)-EE": ["Callum-EE"],
  "English (Australian)-EE": ["Charlie-EE"],
  "English (Swedish)-EE": ["Charlotte-EE"],
  "Latvian-EN": ["Kristaps-EN"],
  "Basque-EN": ["Aitor-EN", "Leire-EN"],
  "Galician-EN": ["Amada-EN", "Gonzalo-EN"],
  "Mongolian-EN": ["Ankhmaa-EN", "Ganbaatar-EN"],
  "Albanian-EN": ["Arben-EN", "Besa-EN"],
  "French (Swiss)-EN": ["Ariane-EN", "Matthieu-EN"],
  "Sundanese-EN": ["Asyifa-EN", "Atep-EN"],
  "Pashto-EN": ["Badrai-EN", "Dilawar-EN"],
  "Odia-EN": ["Baisali-EN", "Ramakanta-EN"],
  "Somali-EN": ["Cabdi-EN", "Xawa-EN"],
  "Maltese-EN": ["Corazon-EN", "Dominic-EN"],
  "Bulgarian-EN": ["Desislava-EN", "Kiril-EN"],
  "Sinhala-EN": ["Dilhani-EN", "Sanath-EN"],
  "English (Filipino accent)-EN": ["Elma-EN", "Manny-EN"],
  "German (Austrian)-EN": ["Franz-EN", "Fritzi-EN"],
  "German (Swiss)-EN": ["Heidi-EN", "Ursina-EN"],
  "Icelandic-EN": ["Ingvar-EN", "Steinunn-EN"],
  "Javanese-EN": ["Isyana-EN", "Riyanto-EN"],
  "Assamese-EN": ["Jahnu-EN", "Rimpi-EN"],
  "Slovene-EN": ["Janez-EN", "Mojca-EN"],
  "Croatian-EN": ["Jasna-EN", "Zoran-EN"],
  "Afrikaans-EN": ["Jochem-EN", "Rolanda-EN"],
  "Estonian-EN": ["Kaarel-EN", "Pille-EN"],
  "Telugu-EN": ["Lalita-EN", "Ramakrishna-EN"],
  "Nepali-EN": ["Lhakpa-EN", "Tenzing-EN"],
  "Bangla (Bangladesh accent)-EN": ["Mahiya-EN", "Salman-EN"],
  "Spanish (Puerto Rican accent)-EN": ["Margarita-EN", "Rodrigo-EN"],
  "Zulu-EN": ["Menzi-EN", "Nandi-EN"],
  "Bosnian-EN": ["Mujo-EN", "Suada-EN"],
  "Swahili-EN": ["Ngina-EN", "Uhuru-EN"],
  "Macedonian-EN": ["Nina-EN", "Vlatko-EN"],
  "Georgian-EN": ["Nino-EN", "Tornike-EN"],
  "Khmer-EN": ["Nisa-EN", "Sovath-EN"],
  "Armenian-EN": ["Nune-EN", "Tigran-EN"],
  "English (Nigerian accent)-EN": ["Obinna-EN", "Thandiwe-EN"],
  "Lao-EN": ["Outhine-EN", "Tonkham-EN"],
  "English (Canadian)-EN": ["Pamela-EN", "Ryan-EN"],
  "Persian-EN": ["Reza-EN", "Shohreh-EN"],
  "Burmese-EN": ["Sanda-EN", "Zeya-EN"],
  "Azerbaijani-EN": ["Tofiq-EN", "Zemfira-EN"],
  "Greek-EN": ["Afroditi-EN", "Dimitris-EN", "Eleni-EN"],
  "English (South African accent)-EN": ["Aletta-EN", "Charlize-EN", "Piet-EN"],
  "Irish-EN": ["Aoife-EN", "Dearbhla-EN", "Eamon-EN"],
  "Lithuanian-EN": ["Arvydas-EN", "Jurga-EN", "Vaida-EN"],
  "English (New Zealand accent)-EN": ["Brooke-EN", "Keith-EN", "Rose-EN"],
  "Uzbek-EN": ["Dilnoza-EN", "Shavkat-EN", "Zulfiya-EN"],
  "Hungarian-EN": ["Eszter-EN", "Krisztina-EN", "Vilmos-EN"],
  "French (Belgian)-EN": ["Fabrice-EN", "Justine-EN", "Laetitia-EN"],
  "Slovak-EN": ["Ivana-EN", "Juraj-EN", "Zuzana-EN"],
  "Ukrainian-EN": ["Oleksandr-EN", "Olena-EN", "Svitlana-EN"],
  "Malayalam-EN": ["Ajay-EN", "Karthika-EN", "Murali-EN", "Uma-EN"],
  "Romanian-EN": ["Alexandru-EN", "Alina-EN", "Ioana-EN", "Loredana-EN"],
  "Amharic-EN": ["Amleset-EN", "Girum-EN", "Seble-EN", "Tamagne-EN"],
  "Kannada-EN": ["Anil-EN", "Bhavana-EN", "Nabha-EN", "Rahul-EN"],
  "Thai-EN": ["Anong-EN", "Malee-EN", "Somsak-EN", "Suwanna-EN"],
  "Tamil-EN": ["Aparna-EN", "Shruti-EN", "Vijay-EN", "Vikram-EN"],
  "Bangla (West Bengal Indian accent)-EN": ["Arpita-EN", "Biswajit-EN", "Prosenjit-EN", "Sunerah-EN"],
  "Gujarati-EN": ["Asha-EN", "Manasi-EN", "Pratik-EN", "Ramesh-EN"],
  "Czech-EN": ["Barbora-EN", "Jana-EN", "Ladislav-EN", "Petra-EN"],
  "English (Irish accent)-EN": ["Bronagh-EN", "Cillian-EN", "Orla-EN", "Saoirse-EN"],
  "Urdu-EN": ["Fahad-EN", "Imran-EN", "Mawra-EN", "Sanam-EN"],
  "English (British)-EE": ["George-EE", "Alice-EE", "Daniel-EE", "Lily-EE"],
  "Serbian-EN": ["Lazar-EN", "Lazar-latin-EN", "Milica-EN", "Milica-latin-EN"],
  "Catalan-EN": ["Abril-EN", "Jordi-EN", "Laia-EN", "Mireia-EN", "Silvia-EN"]
}

const languagesWithVoice=[]

for(const [key,value] of Object.entries(languages)){

  // const voices=value.map((item) => item.split('-');
  languagesWithVoice.push({language:key,voices:value})
}
console.log(languagesWithVoice)
export {languages,languagesWithVoice};

const languageFlags=[
  { "language": "Afrikaans", "flag": "🇿🇦" },
  { "language": "Albanian", "flag": "🇦🇱" },
  { "language": "Amharic", "flag": "🇪🇹" },
  { "language": "Arabic", "flag": "🇸🇦" },
  { "language": "Armenian", "flag": "🇦🇲" },
  { "language": "Azerbaijani", "flag": "🇦🇿" },
  { "language": "Basque", "flag": "🇪🇸" },
  { "language": "Belarusian", "flag": "🇧🇾" },
  { "language": "Bengali", "flag": "🇧🇩" },
  { "language": "Bosnian", "flag": "🇧🇦" },
  { "language": "Bulgarian", "flag": "🇧🇬" },
  { "language": "Burmese", "flag": "🇲🇲" },
  { "language": "Catalan", "flag": "🇪🇸" },
  { "language": "Chinese (Simplified)", "flag": "🇨🇳" },
  { "language": "Chinese (Traditional)", "flag": "🇭🇰" },
  { "language": "Croatian", "flag": "🇭🇷" },
  { "language": "Czech", "flag": "🇨🇿" },
  { "language": "Danish", "flag": "🇩🇰" },
  { "language": "Dutch", "flag": "🇳🇱" },
  { "language": "English", "flag": "🇬🇧" },
  { "language": "English (US)", "flag": "🇺🇸" },
  { "language": "Estonian", "flag": "🇪🇪" },
  { "language": "Filipino", "flag": "🇵🇭" },
  { "language": "Finnish", "flag": "🇫🇮" },
  { "language": "French", "flag": "🇫🇷" },
  { "language": "Georgian", "flag": "🇬🇪" },
  { "language": "German", "flag": "🇩🇪" },
  { "language": "Greek", "flag": "🇬🇷" },
  { "language": "Gujarati", "flag": "🇮🇳" },
  { "language": "Hebrew", "flag": "🇮🇱" },
  { "language": "Hindi", "flag": "🇮🇳" },
  { "language": "Hungarian", "flag": "🇭🇺" },
  { "language": "Icelandic", "flag": "🇮🇸" },
  { "language": "Indonesian", "flag": "🇮🇩" },
  { "language": "Italian", "flag": "🇮🇹" },
  { "language": "Japanese", "flag": "🇯🇵" },
  { "language": "Kannada", "flag": "🇮🇳" },
  { "language": "Kazakh", "flag": "🇰🇿" },
  { "language": "Khmer", "flag": "🇰🇭" },
  { "language": "Korean", "flag": "🇰🇷" },
  { "language": "Kurdish", "flag": "🇮🇶" },
  { "language": "Lao", "flag": "🇱🇦" },
  { "language": "Latvian", "flag": "🇱🇻" },
  { "language": "Lithuanian", "flag": "🇱🇹" },
  { "language": "Macedonian", "flag": "🇲🇰" },
  { "language": "Malay", "flag": "🇲🇾" },
  { "language": "Malayalam", "flag": "🇮🇳" },
  { "language": "Maltese", "flag": "🇲🇹" },
  { "language": "Mongolian", "flag": "🇲🇳" },
  { "language": "Nepali", "flag": "🇳🇵" },
  { "language": "Norwegian", "flag": "🇳🇴" },
  { "language": "Pashto", "flag": "🇦🇫" },
  { "language": "Persian", "flag": "🇮🇷" },
  { "language": "Polish", "flag": "🇵🇱" },
  { "language": "Portuguese", "flag": "🇵🇹" },
  { "language": "Punjabi", "flag": "🇮🇳" },
  { "language": "Romanian", "flag": "🇷🇴" },
  { "language": "Russian", "flag": "🇷🇺" },
  { "language": "Serbian", "flag": "🇷🇸" },
  { "language": "Sinhala", "flag": "🇱🇰" },
  { "language": "Slovak", "flag": "🇸🇰" },
  { "language": "Slovenian", "flag": "🇸🇮" },
  { "language": "Somali", "flag": "🇸🇴" },
  { "language": "Spanish", "flag": "🇪🇸" },
  { "language": "Swahili", "flag": "🇰🇪" },
  { "language": "Swedish", "flag": "🇸🇪" },
  { "language": "Tamil", "flag": "🇮🇳" },
  { "language": "Telugu", "flag": "🇮🇳" },
  { "language": "Thai", "flag": "🇹🇭" },
  { "language": "Turkish", "flag": "🇹🇷" },
  { "language": "Ukrainian", "flag": "🇺🇦" },
  { "language": "Urdu", "flag": "🇵🇰" },
  { "language": "Uzbek", "flag": "🇺🇿" },
  { "language": "Vietnamese", "flag": "🇻🇳" },
  { "language": "Zulu", "flag": "🇿🇦" }
]